### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by id628** [Herjar/radarr_sonarr_watchmon#1]
Did the Trakt API change? Nothing's changed on my end, but it suddenly stopped working:

```
~/radarr_sonarr_watchmon$ venv/bin/python radarr_sonarr_watchmon.py 
Radarr:
 Trakt: movies watches in last 30 days:
Traceback (most recent call last):
  File "radarr_sonarr_watchmon.py", line 330, in <module>
    app.radarr(recent_days, radarr_address, radarr_apikey)
  File "radarr_sonarr_watchmon.py", line 95, in radarr
    movies_watched_recently_imdbids = self.trakt_get_movies(recent_days)
  File "radarr_sonarr_watchmon.py", line 86, in trakt_get_movies
    for movie in Trakt['sync/history'].movies(start_at=recent_date, pagination=True):
TypeError: 'NoneType' object is not iterable

```

**Comment by Herjar** [comment]
Hmm it is working here. Try to authenticate again maybe?

**Comment by id628** [comment]
Thanks. Reading through the code showed me it stores the authorization in .auth.pkl - I renamed it out of the way and it asked me to reauthenticate. Before, it just errored out as above.
