### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by id628** [Herjar/radarr_sonarr_watchmon#17]
Is anyone still using this?

It's stopped working for me, and I'm not sure it's a problem on my end or with an API. I have re-authed to make sure it's not just that.

```
(env) media@media:~/radarr_sonarr_watchmon$ python3 radarr_sonarr_watchmon.py
Movies:
 Trakt: Movies watched in last 5 days:

 Radarr:
  * Movies will be unmonitored in Radarr

  Movies found and changed in Radarr:
Traceback (most recent call last):
  File "/home/media/radarr_sonarr_watchmon/env/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/media/radarr_sonarr_watchmon/radarr_sonarr_watchmon.py", line 534, in <module>
    app.radarr()
  File "/home/media/radarr_sonarr_watchmon/radarr_sonarr_watchmon.py", line 202, in radarr
    movies = response.json()
  File "/home/media/radarr_sonarr_watchmon/env/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(env) media@media:~/radarr_sonarr_watchmon$ pip3 install -r requirements.txt.orig
Requirement already satisfied: trakt.py~=3.0.0 in ./env/lib/python3.9/site-packages (from -r requirements.txt.orig (line 1)) (3.0.0)
Requirement already satisfied: requests in ./env/lib/python3.9/site-packages (from -r requirements.txt.orig (line 2)) (2.31.0)
Requirement already satisfied: pyyaml in ./env/lib/python3.9/site-packages (from -r requirements.txt.orig (line 3)) (6.0.1)
Requirement already satisfied: six in ./env/lib/python3.9/site-packages (from -r requirements.txt.orig (line 4)) (1.16.0)
Requirement already satisfied: arrow<1.0.0,>=0.10.0 in ./env/lib/python3.9/site-packages (from trakt.py~=3.0.0->-r requirements.txt.orig (line 1)) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./env/lib/python3.9/site-packages (from requests->-r requirements.txt.orig (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.9/site-packages (from requests->-r requirements.txt.orig (line 2)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./env/lib/python3.9/site-packages (from requests->-r requirements.txt.orig (line 2)) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.9/site-packages (from requests->-r requirements.txt.orig (line 2)) (2023.11.17)
Requirement already satisfied: python-dateutil>=2.7.0 in ./env/lib/python3.9/site-packages (from arrow<1.0.0,>=0.10.0->trakt.py~=3.0.0->-r requirements.txt.orig ()
```

**Comment by id628** [comment]
Nevermind, it was a problem with my config.
